### ISSUE TITLE
Error in CORS Police

### ISSUE THREAD

**Issue by santinozaracho** [FRRe-DACS/tp2019#1]
No me es posible usar la api en modo localhost desde el navegador!
Error:
localhost/:1 Access to fetch at 'http://localhost:8080/api/medico/1' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by jorgevillaverde** [comment]
Agregado.
